### ISSUE TITLE
meteor tools 

### ISSUE THREAD

**Issue by Sunmmming** [KunyangHan/interactive-segmentation-editor#2]
Hello, I try to run the repo, but the repo always stops at " Downloading meteor-tools@1.8.2 ". What can I do to fix it?

**Comment by Sunmmming** [comment]
Could you please show some version information about the meteor npm node?

**Comment by KunyangHan** [comment]
> Hello, I try to run the repo, but the repo always stops at " Downloading meteor-tools@1.8.2 ". What can I do to fix it?

Is there any Error? If not, I think it was caused by the network connection, it might take hours to complete meteor download in some areas.

**Comment by Sunmmming** [comment]
Oh, thanks. I have got it.
